/**
 * Voice catalogs for the native Kokoro, Edge, Google Translate, and Mistral
 * speech providers. Synthesis accepts any id in these lists. Edge also accepts
 * any other Microsoft neural short name.
 */

export interface NativeAudioVoice {
  id: string;
  name: string;
}

export const KOKORO_VOICES: NativeAudioVoice[] = [
  { id: "af_alloy", name: "af_alloy (American English, female)" },
  { id: "af_amelia_inno", name: "af_amelia_inno (American English, female)" },
  { id: "af_aoede", name: "af_aoede (American English, female)" },
  { id: "af_bella", name: "af_bella (American English, female)" },
  { id: "af_goodall_inno", name: "af_goodall_inno (American English, female)" },
  { id: "af_heart", name: "af_heart (American English, female)" },
  { id: "af_jadzia", name: "af_jadzia (American English, female)" },
  { id: "af_jessica", name: "af_jessica (American English, female)" },
  { id: "af_kore", name: "af_kore (American English, female)" },
  { id: "af_nicole", name: "af_nicole (American English, female)" },
  { id: "af_nova", name: "af_nova (American English, female)" },
  { id: "af_river", name: "af_river (American English, female)" },
  { id: "af_sarah", name: "af_sarah (American English, female)" },
  { id: "af_sky", name: "af_sky (American English, female)" },
  { id: "af_v0", name: "af_v0 (American English, female)" },
  { id: "af_v0bella", name: "af_v0bella (American English, female)" },
  { id: "af_v0irulan", name: "af_v0irulan (American English, female)" },
  { id: "af_v0nicole", name: "af_v0nicole (American English, female)" },
  { id: "af_v0sarah", name: "af_v0sarah (American English, female)" },
  { id: "af_v0sky", name: "af_v0sky (American English, female)" },
  { id: "am_adam", name: "am_adam (American English, male)" },
  { id: "am_echo", name: "am_echo (American English, male)" },
  { id: "am_eric", name: "am_eric (American English, male)" },
  { id: "am_fenrir", name: "am_fenrir (American English, male)" },
  { id: "am_liam", name: "am_liam (American English, male)" },
  { id: "am_michael", name: "am_michael (American English, male)" },
  { id: "am_onyx", name: "am_onyx (American English, male)" },
  { id: "am_price_inno", name: "am_price_inno (American English, male)" },
  { id: "am_puck", name: "am_puck (American English, male)" },
  { id: "am_santa", name: "am_santa (American English, male)" },
  { id: "am_v0adam", name: "am_v0adam (American English, male)" },
  { id: "am_v0gurney", name: "am_v0gurney (American English, male)" },
  { id: "am_v0michael", name: "am_v0michael (American English, male)" },
  { id: "bf_alice", name: "bf_alice (British English, female)" },
  { id: "bf_emma", name: "bf_emma (British English, female)" },
  { id: "bf_isabella", name: "bf_isabella (British English, female)" },
  { id: "bf_lily", name: "bf_lily (British English, female)" },
  { id: "bf_v0emma", name: "bf_v0emma (British English, female)" },
  { id: "bf_v0isabella", name: "bf_v0isabella (British English, female)" },
  { id: "bm_atten_inno", name: "bm_atten_inno (British English, male)" },
  { id: "bm_daniel", name: "bm_daniel (British English, male)" },
  { id: "bm_fable", name: "bm_fable (British English, male)" },
  { id: "bm_george", name: "bm_george (British English, male)" },
  { id: "bm_lewis", name: "bm_lewis (British English, male)" },
  { id: "bm_v0george", name: "bm_v0george (British English, male)" },
  { id: "bm_v0lewis", name: "bm_v0lewis (British English, male)" },
  { id: "ef_dora", name: "ef_dora (Spanish, female)" },
  { id: "em_alex", name: "em_alex (Spanish, male)" },
  { id: "em_santa", name: "em_santa (Spanish, male)" },
  { id: "ff_siwis", name: "ff_siwis (French, female)" },
  { id: "hf_alpha", name: "hf_alpha (Hindi, female)" },
  { id: "hf_beta", name: "hf_beta (Hindi, female)" },
  { id: "hm_omega", name: "hm_omega (Hindi, male)" },
  { id: "hm_psi", name: "hm_psi (Hindi, male)" },
  { id: "if_sara", name: "if_sara (Italian, female)" },
  { id: "im_nicola", name: "im_nicola (Italian, male)" },
  { id: "jf_alpha", name: "jf_alpha (Japanese, female)" },
  { id: "jf_gongitsune", name: "jf_gongitsune (Japanese, female)" },
  { id: "jf_nezumi", name: "jf_nezumi (Japanese, female)" },
  { id: "jf_tebukuro", name: "jf_tebukuro (Japanese, female)" },
  { id: "jm_kumo", name: "jm_kumo (Japanese, male)" },
  { id: "pf_dora", name: "pf_dora (Brazilian Portuguese, female)" },
  { id: "pm_alex", name: "pm_alex (Brazilian Portuguese, male)" },
  { id: "pm_santa", name: "pm_santa (Brazilian Portuguese, male)" },
  { id: "zf_xiaobei", name: "zf_xiaobei (Chinese, female)" },
  { id: "zf_xiaoni", name: "zf_xiaoni (Chinese, female)" },
  { id: "zf_xiaoxiao", name: "zf_xiaoxiao (Chinese, female)" },
  { id: "zf_xiaoyi", name: "zf_xiaoyi (Chinese, female)" },
  { id: "zm_yunjian", name: "zm_yunjian (Chinese, male)" },
  { id: "zm_yunxi", name: "zm_yunxi (Chinese, male)" },
  { id: "zm_yunxia", name: "zm_yunxia (Chinese, male)" },
  { id: "zm_yunyang", name: "zm_yunyang (Chinese, male)" },
];

export const EDGE_TTS_VOICES: NativeAudioVoice[] = [
  { id: "en-US-AriaNeural", name: "Aria (English US)" },
  { id: "en-US-GuyNeural", name: "Guy (English US)" },
  { id: "en-US-JennyNeural", name: "Jenny (English US)" },
  { id: "en-US-AnaNeural", name: "Ana (English US)" },
  { id: "en-US-AndrewNeural", name: "Andrew (English US)" },
  { id: "en-US-AvaNeural", name: "Ava (English US)" },
  { id: "en-US-BrianNeural", name: "Brian (English US)" },
  { id: "en-US-EmmaNeural", name: "Emma (English US)" },
  { id: "en-US-EricNeural", name: "Eric (English US)" },
  { id: "en-US-MichelleNeural", name: "Michelle (English US)" },
  { id: "en-US-RogerNeural", name: "Roger (English US)" },
  { id: "en-US-SteffanNeural", name: "Steffan (English US)" },
  { id: "en-GB-LibbyNeural", name: "Libby (English UK)" },
  { id: "en-GB-MaisieNeural", name: "Maisie (English UK)" },
  { id: "en-GB-RyanNeural", name: "Ryan (English UK)" },
  { id: "en-GB-SoniaNeural", name: "Sonia (English UK)" },
  { id: "en-AU-NatashaNeural", name: "Natasha (English AU)" },
  { id: "en-AU-WilliamNeural", name: "William (English AU)" },
  { id: "en-IN-NeerjaNeural", name: "Neerja (English IN)" },
  { id: "en-IN-PrabhatNeural", name: "Prabhat (English IN)" },
  { id: "fr-FR-DeniseNeural", name: "Denise (French)" },
  { id: "fr-FR-HenriNeural", name: "Henri (French)" },
  { id: "fr-CA-SylvieNeural", name: "Sylvie (French CA)" },
  { id: "fr-CA-AntoineNeural", name: "Antoine (French CA)" },
  { id: "de-DE-KatjaNeural", name: "Katja (German)" },
  { id: "de-DE-ConradNeural", name: "Conrad (German)" },
  { id: "es-ES-ElviraNeural", name: "Elvira (Spanish)" },
  { id: "es-ES-AlvaroNeural", name: "Alvaro (Spanish)" },
  { id: "es-MX-DaliaNeural", name: "Dalia (Spanish MX)" },
  { id: "es-MX-JorgeNeural", name: "Jorge (Spanish MX)" },
  { id: "pt-BR-FranciscaNeural", name: "Francisca (Portuguese BR)" },
  { id: "pt-BR-AntonioNeural", name: "Antonio (Portuguese BR)" },
  { id: "pt-PT-RaquelNeural", name: "Raquel (Portuguese PT)" },
  { id: "pt-PT-DuarteNeural", name: "Duarte (Portuguese PT)" },
  { id: "it-IT-ElsaNeural", name: "Elsa (Italian)" },
  { id: "it-IT-DiegoNeural", name: "Diego (Italian)" },
  { id: "ja-JP-NanamiNeural", name: "Nanami (Japanese)" },
  { id: "ja-JP-KeitaNeural", name: "Keita (Japanese)" },
  { id: "ko-KR-SunHiNeural", name: "Sun-Hi (Korean)" },
  { id: "ko-KR-InJoonNeural", name: "InJoon (Korean)" },
  { id: "zh-CN-XiaoxiaoNeural", name: "Xiaoxiao (Chinese)" },
  { id: "zh-CN-YunxiNeural", name: "Yunxi (Chinese)" },
  { id: "zh-CN-XiaoyiNeural", name: "Xiaoyi (Chinese)" },
  { id: "zh-CN-YunjianNeural", name: "Yunjian (Chinese)" },
  { id: "zh-TW-HsiaoChenNeural", name: "HsiaoChen (Chinese TW)" },
  { id: "zh-HK-HiuMaanNeural", name: "HiuMaan (Cantonese)" },
  { id: "hi-IN-SwaraNeural", name: "Swara (Hindi)" },
  { id: "hi-IN-MadhurNeural", name: "Madhur (Hindi)" },
  { id: "ar-SA-ZariyahNeural", name: "Zariyah (Arabic)" },
  { id: "ar-SA-HamedNeural", name: "Hamed (Arabic)" },
  { id: "nl-NL-ColetteNeural", name: "Colette (Dutch)" },
  { id: "nl-NL-MaartenNeural", name: "Maarten (Dutch)" },
  { id: "pl-PL-ZofiaNeural", name: "Zofia (Polish)" },
  { id: "pl-PL-MarekNeural", name: "Marek (Polish)" },
  { id: "ru-RU-SvetlanaNeural", name: "Svetlana (Russian)" },
  { id: "ru-RU-DmitryNeural", name: "Dmitry (Russian)" },
  { id: "tr-TR-EmelNeural", name: "Emel (Turkish)" },
  { id: "tr-TR-AhmetNeural", name: "Ahmet (Turkish)" },
  { id: "sv-SE-SofieNeural", name: "Sofie (Swedish)" },
  { id: "sv-SE-MattiasNeural", name: "Mattias (Swedish)" },
  { id: "da-DK-ChristelNeural", name: "Christel (Danish)" },
  { id: "nb-NO-PernilleNeural", name: "Pernille (Norwegian)" },
  { id: "fi-FI-NooraNeural", name: "Noora (Finnish)" },
  { id: "uk-UA-PolinaNeural", name: "Polina (Ukrainian)" },
  { id: "cs-CZ-VlastaNeural", name: "Vlasta (Czech)" },
  { id: "el-GR-AthinaNeural", name: "Athina (Greek)" },
  { id: "he-IL-HilaNeural", name: "Hila (Hebrew)" },
  { id: "th-TH-PremwadeeNeural", name: "Premwadee (Thai)" },
  { id: "vi-VN-HoaiMyNeural", name: "HoaiMy (Vietnamese)" },
  { id: "id-ID-GadisNeural", name: "Gadis (Indonesian)" },
];

export const GOOGLE_TTS_VOICES: NativeAudioVoice[] = [
  { id: "en", name: "English" },
  { id: "en-US", name: "English (United States)" },
  { id: "en-GB", name: "English (United Kingdom)" },
  { id: "en-AU", name: "English (Australia)" },
  { id: "en-IN", name: "English (India)" },
  { id: "fr", name: "French" },
  { id: "fr-FR", name: "French (France)" },
  { id: "fr-CA", name: "French (Canada)" },
  { id: "de", name: "German" },
  { id: "es", name: "Spanish" },
  { id: "es-ES", name: "Spanish (Spain)" },
  { id: "es-US", name: "Spanish (United States)" },
  { id: "it", name: "Italian" },
  { id: "pt", name: "Portuguese" },
  { id: "pt-BR", name: "Portuguese (Brazil)" },
  { id: "pt-PT", name: "Portuguese (Portugal)" },
  { id: "nl", name: "Dutch" },
  { id: "pl", name: "Polish" },
  { id: "ru", name: "Russian" },
  { id: "uk", name: "Ukrainian" },
  { id: "ja", name: "Japanese" },
  { id: "ko", name: "Korean" },
  { id: "zh-CN", name: "Chinese (Simplified)" },
  { id: "zh-TW", name: "Chinese (Traditional)" },
  { id: "yue", name: "Cantonese" },
  { id: "ar", name: "Arabic" },
  { id: "hi", name: "Hindi" },
  { id: "bn", name: "Bengali" },
  { id: "ta", name: "Tamil" },
  { id: "te", name: "Telugu" },
  { id: "tr", name: "Turkish" },
  { id: "vi", name: "Vietnamese" },
  { id: "th", name: "Thai" },
  { id: "id", name: "Indonesian" },
  { id: "ms", name: "Malay" },
  { id: "fil", name: "Filipino" },
  { id: "sv", name: "Swedish" },
  { id: "da", name: "Danish" },
  { id: "no", name: "Norwegian" },
  { id: "fi", name: "Finnish" },
  { id: "el", name: "Greek" },
  { id: "cs", name: "Czech" },
  { id: "hu", name: "Hungarian" },
  { id: "ro", name: "Romanian" },
  { id: "bg", name: "Bulgarian" },
  { id: "hr", name: "Croatian" },
  { id: "sk", name: "Slovak" },
  { id: "sl", name: "Slovenian" },
  { id: "ca", name: "Catalan" },
  { id: "he", name: "Hebrew" },
  { id: "af", name: "Afrikaans" },
  { id: "sw", name: "Swahili" },
];

export const MISTRAL_TTS_VOICES: NativeAudioVoice[] = [
  { id: "en_paul_neutral", name: "Paul - Neutral" },
  { id: "en_paul_confident", name: "Paul - Confident" },
  { id: "en_paul_cheerful", name: "Paul - Cheerful" },
  { id: "en_paul_happy", name: "Paul - Happy" },
  { id: "en_paul_excited", name: "Paul - Excited" },
  { id: "en_paul_sad", name: "Paul - Sad" },
  { id: "en_paul_frustrated", name: "Paul - Frustrated" },
  { id: "en_paul_angry", name: "Paul - Angry" },
  { id: "gb_jane_neutral", name: "Jane - Neutral" },
  { id: "gb_jane_confident", name: "Jane - Confident" },
  { id: "gb_jane_curious", name: "Jane - Curious" },
  { id: "gb_jane_sarcasm", name: "Jane - Sarcasm" },
  { id: "gb_jane_confused", name: "Jane - Confused" },
  { id: "gb_jane_frustrated", name: "Jane - Frustrated" },
  { id: "gb_jane_jealousy", name: "Jane - Jealousy" },
  { id: "gb_jane_sad", name: "Jane - Sad" },
  { id: "gb_jane_shameful", name: "Jane - Shameful" },
  { id: "gb_oliver_neutral", name: "Oliver - Neutral" },
  { id: "gb_oliver_confident", name: "Oliver - Confident" },
  { id: "gb_oliver_cheerful", name: "Oliver - Cheerful" },
  { id: "gb_oliver_curious", name: "Oliver - Curious" },
  { id: "gb_oliver_excited", name: "Oliver - Excited" },
  { id: "gb_oliver_sad", name: "Oliver - Sad" },
  { id: "gb_oliver_angry", name: "Oliver - Angry" },
  { id: "fr_marie_neutral", name: "Marie - Neutral" },
  { id: "fr_marie_happy", name: "Marie - Happy" },
  { id: "fr_marie_excited", name: "Marie - Excited" },
  { id: "fr_marie_curious", name: "Marie - Curious" },
  { id: "fr_marie_sad", name: "Marie - Sad" },
  { id: "fr_marie_angry", name: "Marie - Angry" },
];

const VOICES_BY_PROVIDER: Record<string, NativeAudioVoice[]> = {
  kokoro: KOKORO_VOICES,
  "edge-tts": EDGE_TTS_VOICES,
  "google-tts": GOOGLE_TTS_VOICES,
  gtts: GOOGLE_TTS_VOICES,
  mistral: MISTRAL_TTS_VOICES,
  "mistral-voxtral": MISTRAL_TTS_VOICES,
};

export function speechVoicesForProvider(providerId: string): NativeAudioVoice[] | undefined {
  return VOICES_BY_PROVIDER[providerId];
}
